fitur1/urls.py
from django.conf.urls import url
from .views import index, add_comment


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-comment/$', add_comment, name='add-comment'),
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur1.urls as fitur1
import fitur2.urls as fitur2
#import fitur3.urls as fitur3
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(
        url='/landing/', permanent=True)),
    url(r'^fitur1/', RedirectView.as_view(
        url='/landing/', permanent=True)),
    url(r'^landing/', include(fitur1, namespace='fitur1')),
    #url(r'', include(fitur3, namespace='fitur3')),
    url(r'^profile/', include(fitur2, namespace="fitur2"))

]

fitur1/models.py
from django.db import models

class Lowongan(models.Model):
    perusahaan = models.CharField(max_length=250)
    lowongan = models.TextField()

class Tanggapan(models.Model):
    nama = models.CharField(max_length=250)
    komentar = models.TextField()

fitur1/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from .models import Tanggapan
from django.core import serializers
import json

# Create your views here.

response = {}

# blum selese baru bisa login ke linkedIn doang


def index(request):
    html = 'fitur1/fitur1.html'
    tanggapan = Tanggapan.objects.all()
    response['komentar'] = tanggapan
    return render(request, html, response)

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
        nama = request.POST['nama']
        komentar = request.POST['komentar']

        comment = Tanggapan(nama=nama, komentar=komentar)
        comment.save()
        data = model_to_dict(comment)
        return HttpResponse(data)
    else:
        return HttpResponseRedirect(reverse('fitur1:index'))

def model_to_dict(obj):
    data = serializers.serialize('json', [obj, ])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

fitur1/templates/fitur1/fitur1.html
{% extends "fitur1/layout/base.html" %}
{%load staticfiles%}
{% block content %}

<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <title>Home</title>
        <script type="text/javascript" src="//platform.linkedin.com/in.js">
          api_key: 77hncv61m96quy
          authorize: false
          onLoad: onLinkedInLoad
          scope: r_basicprofile r_emailaddress rw_company_admin
        </script>
</head>

<body>
    <div id="container">	
        <div id="section1" class="section">
            <div id="content">
                <h1>Headline One</h1>
                <p>Lorem ipsum dolor sit amet...</p>
                <script type="in/Login"></script>
                <script src="{% static 'js/login.js' %}"></script>   
            </div> 
        </div>
        
        <div id="section2" class="section">
            <h1>Headline Two</h1>
            <p>Lorem ipsum dolor sit amet...</p>
            <div id="postcontainer">
                <div class=vacancies>
                    <p>ini lowongan</p>
                </div>
                {% if komentar %}
                    {% for komen in komentar %}
                    <div class=comments>
                        <p>{{ komen.komentar }}</p>
                    </div>
                    {% endfor %}
                {% else %}
                    <div class=comments>
                        <p>ini comment</p>
                    </div>
                {% endif %}
                <form id="add-comment" action="#">
                        {% csrf_token %}
                        <label for="field_nama">Nama</label>
                        <input id="field_nama" type="text" name="nama" class="form-control"/>
                        <label for="field_comment">Tanggapan</label>
                        <input id="field_comment" type="text" name="komentar" class="form-control"/>
                        <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var addComment = function(nama, komentar) {
        $.ajax({
            method: "POST",
            url: "{% url 'fitur1:add-comment' %}",
            data: { nama: nama, komentar: komentar},
            success : function (komen) {
                var sesuatu = $.parseJSON(komen)
                console.log(sesuatu)
                html = '<div class=comments> <p>' + 
                        sesuatu.komentar + '</p> </div>'
                $("#postcontainer").append(html)
            },
            error : function (error) {
                alert(error.responseText)
            }
        });
    };

    $("#add-comment").on("submit", function () {
       nama = $("#field_nama").val()
       komentar = $("#field_comment").val()
        addComment(nama, komentar)
        event.preventDefault();
    });
</script>
</html>
{% endblock %}